steps:
# Build the alchemy test image
#
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--target', 'test',
         '--tag', 'gcr.io/$PROJECT_ID/alchemy:test-${SHORT_SHA}',
         '.']
  id: 'build-test-image'

# Run the tests, to prevent having broken
# images. May look unnecessary since there are
# GitHub actions that run tests, however it
# wouldn't hurt to double check.
#
- name: 'gcr.io/cloud-builders/docker'
  args: ['run',
         '--env', 'GOOGLE_AI_PLATFORM_ENABLED=0',
         '--env', 'USE_CLOUD_LOGGING=0',
         'gcr.io/$PROJECT_ID/alchemy:test-${SHORT_SHA}',
         'sh', 'ci/run_tests.sh']
  wait_for: ['build-test-image']
  id: 'run-tests'

# Build the target image
#
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--target', '${_TARGET}',
         '--cache-from', 'gcr.io/$PROJECT_ID/alchemy:test-${SHORT_SHA}',
         '--tag', 'gcr.io/$PROJECT_ID/alchemy:${_TARGET}-${SHORT_SHA}',
         '.']
  wait_for: ['run-tests']
  id: 'build-target-image'

timeout: 1200s
images:
  - 'gcr.io/$PROJECT_ID/alchemy:${_TARGET}-${SHORT_SHA}'
