version: '3.4'

# https://docs.docker.com/compose/compose-file/#extension-fields
x-volumes:
  &default-volumes
  - $GCLOUD_LOCAL_DIR:/root/.config/gcloud
  # By default the credential location is under $GCLOUD_LOCAL_DIR/credentials.
  # Unless it is customized, there is no need to use the next line.
  #- $GOOGLE_APPLICATION_CREDENTIALS_LOCAL_DIR:/root/.secret
  - $FILESTORE_LOCAL_DIR:/app/__filestore

services:

  admin_server:
    env_file: .env
    image: &img gcr.io/nlp-flywheel/alchemy:latest
    expose:
      - 5000
    volumes: *default-volumes
    command: [
        '--flask-env', 'production',
        '--flask-host', '0.0.0.0',
        '--flask-port', '5000',
        'admin_server'
    ]
    environment:
      - SCRIPT_NAME=/admin
    depends_on:
      - redis

  annotation_server:
    env_file: .env
    image: *img
    expose:
      - 5001
    volumes: *default-volumes
    command: [
        '--flask-env', 'production',
        '--flask-host', '0.0.0.0',
        '--flask-port', '5001',
        'annotation_server'
    ]
    depends_on:
      - redis
      - admin_server

  ar_celery:
    env_file: .env
    image: *img
    volumes: *default-volumes
    entrypoint: ["celery", "--app=alchemy.ar.ar_celery", "worker", "-Q", "ar_celery", "-c", "2", "--autoscale=100,2", "-l", "info", "--max-tasks-per-child", "1", "-n", "ar_celery"]
    depends_on:
      - redis
      - admin_server

  train_celery:
    env_file: .env
    image: *img
    volumes: *default-volumes
    entrypoint: ["celery", "--app=alchemy.train.train_celery", "worker", "-Q", "train_celery", "-c", "2", "--autoscale=100,2", "-l", "info", "--max-tasks-per-child", "1", "-n", "train_celery"]
    depends_on:
      - redis
      - admin_server

  gcp_celery:
    env_file: .env
    image: *img
    volumes: *default-volumes
    entrypoint: ["celery", "--app=alchemy.train.gcp_celery", "worker", "-Q", "gcp_celery", "-c", "5", "--autoscale=100,2", "-l", "info", "-n", "gcp_celery"]
    depends_on:
      - redis
      - admin_server
  nginx:
    env_file:
      - .env
    environment:
      - ANNOTATION_SERVER_UWSGI=annotation_server:5001
      - ADMIN_SERVER_UWSGI=admin_server:5000
    image: nginx:stable-alpine
    volumes:
      - .conf/nginx:/etc/nginx/templates
      - /etc/letsencrypt/challenge:/var/www/letsencrypt
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - admin_server
      - annotation_server
    links:
      - admin_server
      - annotation_server
    ports:
    - "80:80"
    - "443:443"

  redis:
    image: "redis:alpine"
