"""test adding a fake field

Revision ID: 044204823448
Revises: 740c83f3631f
Create Date: 2020-04-16 18:31:02.335133

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '044204823448'
down_revision = '740c83f3631f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label',
                  sa.Column('fake_field', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('label') as batch_op:
        batch_op.drop_column('fake_field')
    # op.drop_column('label', 'fake_field') # This does not work with sqlite
    # ### end Alembic commands ###
