"""Add label column to Model

Revision ID: 3360fe3522aa
Revises: 779682965b20
Create Date: 2020-05-14 13:03:58.036357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3360fe3522aa'
down_revision = '779682965b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_model_label'), [
                              'label'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_label'))
        batch_op.drop_column('label')

    # ### end Alembic commands ###
