"""first commit

Revision ID: 740c83f3631f
Revises: 
Create Date: 2020-04-16 14:27:48.517649

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '740c83f3631f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_type',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_entity_type_name'), 'entity_type', ['name'],
                    unique=True)
    op.create_table('entity',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=True),
                    sa.Column('entity_type_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['entity_type_id'],
                                            ['entity_type.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_entity_name'), 'entity', ['name'], unique=True)
    op.create_table('label',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=True),
                    sa.Column('entity_type_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['entity_type_id'],
                                            ['entity_type.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_label_name'), 'label', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_label_name'), table_name='label')
    op.drop_table('label')
    op.drop_index(op.f('ix_entity_name'), table_name='entity')
    op.drop_table('entity')
    op.drop_index(op.f('ix_entity_type_name'), table_name='entity_type')
    op.drop_table('entity_type')
    # ### end Alembic commands ###
