"""adding label owner

Revision ID: 7e4b67c43039
Revises: 7c026be6d31e
Create Date: 2020-07-15 17:49:37.658944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e4b67c43039'
down_revision = '7c026be6d31e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label_owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_label_owner_owner_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_label_owner'))
    )
    with op.batch_alter_table('label_owner', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_label_owner_label'), ['label'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('label_owner', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_label_owner_label'))

    op.drop_table('label_owner')
    # ### end Alembic commands ###
