"""remove relationship between task and model

Revision ID: a94911ed125b
Revises: e05604e8db05
Create Date: 2020-06-23 18:09:14.044884

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a94911ed125b"
down_revision = "3360fe3522aa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("model", schema=None) as batch_op:
        batch_op.drop_constraint("fk_model_task_id_task", type_="foreignkey")
        batch_op.drop_column("task_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("model", schema=None) as batch_op:
        batch_op.add_column(sa.Column("task_id", sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(
            "fk_model_task_id_task", "task", ["task_id"], ["id"]
        )

    # ### end Alembic commands ###
