"""Adding weights to annotations

Revision ID: fe338e2849ef
Revises: 610c9b5a2493
Create Date: 2020-07-14 16:38:11.455024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe338e2849ef'
down_revision = '7e4b67c43039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classification_annotation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classification_annotation', schema=None) as batch_op:
        batch_op.drop_column('weight')

    # ### end Alembic commands ###
