# This build file is triggered on each commit to master
# in which some files in alchemy/train/nodeps/** are
# touched.
# This is configured in the GCP console > cloud build >
# triggers. See:
# https://cloud.google.com/cloud-build/docs/automating-builds/create-github-app-triggers#creating_github_app_triggers_2
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--tag', 'gcr.io/$PROJECT_ID/alchemy-training:$_TARGET-$SHORT_SHA',
         '.']
  id: 'build-training-image'
timeout: 2400s  # It is a quite large image just pushing the image takes ~25 minutes
images:
  - 'gcr.io/$PROJECT_ID/alchemy-training'
