steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--tag', 'gcr.io/$PROJECT_ID/alchemy-training:$_TARGET-$SHORT_SHA',
         '.']
  id: 'build-training-image'
timeout: 2400s  # It is a quite large image just pushing the image takes ~25 minutes
images:
  - 'gcr.io/$PROJECT_ID/alchemy-training'
