name: CI

on:
  push:
    branches: master
  pull_request:
    branches: ['master']

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Set up dependencies
      run: |
        echo Installing test requirements
        pip install -r requirements/test.txt
        sh ci/install_deps.sh --no-gcp --no-spacy

        ALCHEMY_FILESTORE_DIR="$RUNNER_TEMP/__filestore"
        mkdir -p "$ALCHEMY_FILESTORE_DIR"

        echo "ALCHEMY_DATABASE_URI=\"sqlite://$RUNNER_TEMP/alchemy.db\"" >> $GITHUB_ENV
        echo "ALCHEMY_FILESTORE_DIR=\"$RUNNER_TEMP/__filestore\"" >> $GITHUB_ENV
        echo "SECRET_KEY=randomsecretkeytopreventerrors" >> $GITHUB_ENV
    - name: Run tests
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        COVERAGE: 1
      run: |
        export TEST_ARGS="--basetemp=$RUNNER_TEMP"
        sh ci/run_tests.sh

