name: CI

on:
  push:
    branches: master
  pull_request:
    branches: ['master']

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Set up dependencies
      run: |
        echo Installing base requirements
        pip install -r requirements.txt
        sh ci/install_deps.sh --no-gcp --no-spacy

        ALCHEMY_FILESTORE_DIR="$RUNNER_TEMP/__filestore"
        mkdir -p "$ALCHEMY_FILESTORE_DIR"

        echo "ALCHEMY_DATABASE_URI=\"sqlite://$RUNNER_TEMP/alchemy.db\"" >> $GITHUB_ENV
        echo "ALCHEMY_FILESTORE_DIR=\"$RUNNER_TEMP/__filestore\"" >> $GITHUB_ENV
    - name: Run tests
      run: |
        export TEST_ARGS="--basetemp=$RUNNER_TEMP"
        sh ci/run_tests.sh

