name: CI

on:
  push:
    branches: master
  pull_request:
    branches: ['master']

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Set up dependencies
      run: |
        pip install -r requirements.txt
        sh ci/install_deps.sh
    - name: Run tests
      run: |
        sh ci/run_tests.sh

